#!/system/bin/sh

version="LOS12.1/14.1 suez - v.002 da[sh]";

L="log -p i -t alsa_trigger"
$L " "
$L "   __   ALSA  .__   $version"
$L " _/  |________|__| ____   ____   ___________  "
$L " \   __\_  __ \  |/ ___\ / ___\_/ __ \_  __ \ "
$L "  |  |  |  | \/  / /_/  > /_/  >  ___/|  | \/ "
$L "  |__|  |__|  |__\___  /\___  / \___  >__|    "
$L "                /_____//_____/      \/        "
$L " spelcheck@xda"
$L " "

# @todo - make this a legitimate rc.d service with a pid, start/stop/restart actions
# @future - continue work on 'bash' branch so that it's modular, configurable and usable for all platforms and configurations (named 'ALSA_trigger').

# Send intitial platform-specific commands to ALSA.
alsa_amixer cset name='Headset_Speaker_Amp_Switch' 'On';

# Clear logcat so we don't trigger based on stale data.
logcat -c;

# Launch a separate piped logcat grep process to search for the trigger text, then directly send controls to ALSA.

# search: 'newName=h2w newState=1 headsetState=1|newName=h2w newState=2 headsetState=2'
# Turn on Headset_Speaker_Amp_Switch
# Mute Speaker_PGAL_GAIN
# Mute Speaker_PGAR_GAIN

logcat | grep -E --line-buffered 'newName=h2w newState=1 headsetState=1|newName=h2w newState=2 headsetState=2' | while read line; do alsa_amixer cset name='Headset_Speaker_Amp_Switch' 'On'; alsa_amixer cset name='Speaker_PGAL_GAIN' 'Mute'; alsa_amixer cset name='Speaker_PGAR_GAIN' 'Mute'; done &

# search: 'newName=h2w newState=0 headsetState=0'
# Turn off Headset_Speaker_Amp_Switch
# Set Speaker_PGAL_GAIN to 8Db
# Set Speaker_PGAR_GAIN to 8Db
# Turn on Speaker_Amp_Switch 

logcat | grep -E --line-buffered 'newName=h2w newState=0 headsetState=0' | while read line; do alsa_amixer cset name='Headset_Speaker_Amp_Switch' 'Off'; alsa_amixer cset name='Speaker_PGAL_GAIN' '8Db'; alsa_amixer cset name='Speaker_PGAR_GAIN' '8Db'; alsa_amixer cset name='Speaker_Amp_Switch' 'On'; done &
